apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: usu1nw3p6-nodejs
  janus-idp.io/tekton: usu1nw3p6-nodejs
  backstage.io/kubernetes-id: usu1nw3p6-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: usu1nw3p6-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
